const stringMethods = [
  { label: 'constructor', detail: 'Obj' },
  { label: 'anchor', detail: 'Str' },
  { label: 'big', detail: 'Str' },
  { label: 'blink', detail: 'Str' },
  { label: 'bold', detail: 'Str' },
  { label: 'charAt', detail: 'Str' },
  { label: 'charCodeAt', detail: 'Str' },
  { label: 'codePointAt', detail: 'Str' },
  { label: 'endsWith', detail: 'Str' },
  { label: 'fontcolor', detail: 'Str' },
  { label: 'fontsize', detail: 'Str' },
  { label: 'fixed', detail: 'Str' },
  { label: 'italics', detail: 'Str' },
  { label: 'link', detail: 'Str' },
  { label: 'localeCompare', detail: 'Str' },
  { label: 'match', detail: 'Str' },
  { label: 'matchAll', detail: 'Str' },
  { label: 'normalize', detail: 'Str' },
  { label: 'padEnd', detail: 'Str' },
  { label: 'padStart', detail: 'Str' },
  { label: 'repeat', detail: 'Str' },
  { label: 'replace', detail: 'Str' },
  { label: 'replaceAll', detail: 'Str' },
  { label: 'search', detail: 'Str' },
  { label: 'small', detail: 'Str' },
  { label: 'split', detail: 'Str' },
  { label: 'strike', detail: 'Str' },
  { label: 'sub', detail: 'Str' },
  { label: 'substr', detail: 'Str' },
  { label: 'substring', detail: 'Str' },
  { label: 'sup', detail: 'Str' },
  { label: 'startsWith', detail: 'Str' },
  { label: 'trim', detail: 'Str' },
  { label: 'trimStart', detail: 'Str' },
  { label: 'trimLeft', detail: 'Str' },
  { label: 'trimEnd', detail: 'Str' },
  { label: 'trimRight', detail: 'Str' },
  { label: 'toLocaleLowerCase', detail: 'Str' },
  { label: 'toLocaleUpperCase', detail: 'Str' },
  { label: 'toLowerCase', detail: 'Str' },
  { label: 'toUpperCase', detail: 'Str' },
  { label: 'toExponential', detail: 'Num' },
  { label: 'toFixed', detail: 'Num' },
  { label: 'toPrecision', detail: 'Num' },
  { label: 'copyWithin', detail: 'Arr' },
  { label: 'fill', detail: 'Arr' },
  { label: 'find', detail: 'Arr' },
  { label: 'findIndex', detail: 'Arr' },
  { label: 'pop', detail: 'Arr' },
  { label: 'push', detail: 'Arr' },
  { label: 'reverse', detail: 'Arr' },
  { label: 'shift', detail: 'Arr' },
  { label: 'unshift', detail: 'Arr' },
  { label: 'sort', detail: 'Arr' },
  { label: 'splice', detail: 'Arr' },
  { label: 'join', detail: 'Arr' },
  { label: 'keys', detail: 'Arr' },
  { label: 'entries', detail: 'Arr' },
  { label: 'values', detail: 'Arr' },
  { label: 'forEach', detail: 'Arr' },
  { label: 'filter', detail: 'Arr' },
  { label: 'flat', detail: 'Arr' },
  { label: 'flatMap', detail: 'Arr' },
  { label: 'map', detail: 'Arr' },
  { label: 'every', detail: 'Arr' },
  { label: 'some', detail: 'Arr' },
  { label: 'reduce', detail: 'Arr' },
  { label: 'reduceRight', detail: 'Arr' },
  { label: 'findLast', detail: 'Arr' },
  { label: 'findLastIndex', detail: 'Arr' },
  { label: 'toDateString', detail: 'Date' },
  { label: 'toTimeString', detail: 'Date' },
  { label: 'toISOString', detail: 'Date' },
  { label: 'toUTCString', detail: 'Date' },
  { label: 'toGMTString', detail: 'Date' },
  { label: 'getDate', detail: 'Date' },
  { label: 'setDate', detail: 'Date' },
  { label: 'getDay', detail: 'Date' },
  { label: 'getFullYear', detail: 'Date' },
  { label: 'setFullYear', detail: 'Date' },
  { label: 'getHours', detail: 'Date' },
  { label: 'setHours', detail: 'Date' },
  { label: 'getMilliseconds', detail: 'Date' },
  { label: 'setMilliseconds', detail: 'Date' },
  { label: 'getMinutes', detail: 'Date' },
  { label: 'setMinutes', detail: 'Date' },
  { label: 'getMonth', detail: 'Date' },
  { label: 'setMonth', detail: 'Date' },
  { label: 'getSeconds', detail: 'Date' },
  { label: 'setSeconds', detail: 'Date' },
  { label: 'getTime', detail: 'Date' },
  { label: 'setTime', detail: 'Date' },
  { label: 'getTimezoneOffset', detail: 'Date' },
  { label: 'getUTCDate', detail: 'Date' },
  { label: 'setUTCDate', detail: 'Date' },
  { label: 'getUTCDay', detail: 'Date' },
  { label: 'getUTCFullYear', detail: 'Date' },
  { label: 'setUTCFullYear', detail: 'Date' },
  { label: 'getUTCHours', detail: 'Date' },
  { label: 'setUTCHours', detail: 'Date' },
  { label: 'getUTCMilliseconds', detail: 'Date' },
  { label: 'setUTCMilliseconds', detail: 'Date' },
  { label: 'getUTCMinutes', detail: 'Date' },
  { label: 'setUTCMinutes', detail: 'Date' },
  { label: 'getUTCMonth', detail: 'Date' },
  { label: 'setUTCMonth', detail: 'Date' },
  { label: 'getUTCSeconds', detail: 'Date' },
  { label: 'setUTCSeconds', detail: 'Date' },
  { label: 'getYear', detail: 'Date' },
  { label: 'setYear', detail: 'Date' },
  { label: 'toJSON', detail: 'Date' },
  { label: 'toLocaleDateString', detail: 'Date' },
  { label: 'toLocaleTimeString', detail: 'Date' },
  { label: 'exec', detail: 'RegExp' },
  { label: 'compile', detail: 'RegExp' },
  { label: 'test', detail: 'RegExp' },
  { label: '__defineGetter__', detail: '' },
  { label: '__defineSetter__', detail: '' },
  { label: 'hasOwnProperty', detail: '' },
  { label: '__lookupGetter__', detail: '' },
  { label: '__lookupSetter__', detail: '' },
  { label: 'isPrototypeOf', detail: '' },
  { label: 'propertyIsEnumerable', detail: '' },
  { label: 'toString', detail: '' },
  { label: 'valueOf', detail: '' },
  { label: 'toLocaleString', detail: '' },
  { label: 'concat', detail: 'Str,Arr' },
  { label: 'includes', detail: 'Str,Arr' },
  { label: 'indexOf', detail: 'Str,Arr' },
  { label: 'lastIndexOf', detail: 'Str,Arr' },
  { label: 'slice', detail: 'Str,Arr' },
  { label: 'at', detail: 'Str,Arr' },
];

export function myCompletions(context) {
  let word = context.matchBefore(/\w*/);
  if (word.from == word.to && !context.explicit) return null;
  return {
    from: word.from,
    options: [
      ...stringMethods.map((item) => ({
        label: item.label,
        type: 'variable',
        detail:  item.detail ? `(${item.detail})` : '',
      })),
      // { label: "match", type: "keyword"},
      // {label: "toUpperCase", type: "variable", info: "(World)"},
      // {label: "magic", type: "text", apply: "⠁⭒*.✩.*⭒⠁", detail: "macro"}
    ],
  };
}
